name: Upload Python Package

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Release
        if: github.ref == 'refs/heads/main'
        uses: python-semantic-release/python-semantic-release@v7.34.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pypi_token: ${{ secrets.PYPI_TOKEN }}

  pypi-publish:
      name: upload release to PyPI
      runs-on: ubuntu-latest
      # Specifying a GitHub environment is optional, but strongly encouraged
      environment: release
      steps:
        - name: build
          run: |
            python -m pip install --upgrade pip
            pip install setuptools wheel
            python setup.py sdist bdist_wheel
        - name: pypi-publish
          uses: pypa/gh-action-pypi-publish@v1.5.0
          with:
            user: __token__
            password: ${{ secrets.PYPI_API_TOKEN }}
