name: Tests

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          version: latest
      - run: ruff check
      - run: ruff format --check
  test:
    runs-on: ubuntu-latest
    needs: ruff
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install and configure Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true
      - name: Install dependencies
        run: poetry install
      - name: Pytest
        run: |
          poetry run pytest
